export type Project = {
  projectName: string;
  startDate: string;
  endDate: string;
  currentlyWorking: boolean;
  skills: string[];
  imageRefs: string[];
  description: string;
  note: string;
  associatedWith: string[];
};

export const PROJECT_INDEX: Project[] = [
  {
    projectName: "ARCHiVER: Digital Accession Record System",
    startDate: "2024-04",
    endDate: "2024-06",
    currentlyWorking: false,
    skills: [
      "REST APIs",
      "Full-Stack Development",
      "Bootstrap (Framework)",
      "Flask",
      "MySQL",
      "Database Management System (DBMS)",
      "Web Development",
    ],
    imageRefs: [],
    description:
      "A digital accession record management system built with Flask, MySQL, and AdminLTE. Streamlines record management with multi-user functionality and role-based permissions for secure, organized access. Features a searchable table for locating accession records by attributes like ISBN, title, and author, with an intuitive CRUD system accessible via the data table and control menu. The UI is enhanced with AdminLTE (a Bootstrap-based CSS framework), Jinja2, FontAwesome, jQuery, and AJAX. Archived as of May 2025.",
    note: "",
    associatedWith: ["Don Bosco Technical College, Mandaluyong"],
  },
  {
    projectName: "Cerebral: Local Password Manager",
    startDate: "2024-06",
    endDate: "2024-12",
    currentlyWorking: false,
    skills: [
      "REST APIs",
      "Full-Stack Development",
      "Bootstrap (Framework)",
      "Jinja",
      "HTML",
      "Web Development",
      "Flask",
      "Python (Programming Language)",
      "MySQL",
      "Cascading Style Sheets (CSS)",
      "API Development",
    ],
    imageRefs: [],
    description:
      "A Flask web application integrating MySQL and AdminLTE, originally a passion project converted into an academic project. Designed to securely and efficiently store passwords and account details locally without third-party applications. Features a secure login authentication process with encryption and decryption to protect user credentials, plus a registration system that lets users create personalized profiles for managing their stored information. Development halted indefinitely as of May 2025.",
    note: "",
    associatedWith: ["Don Bosco Technical College, Mandaluyong"],
  },
  {
    projectName: "Midas Financial Tracker",
    startDate: "2024-11",
    endDate: "2025-03",
    currentlyWorking: false,
    skills: [
      "REST APIs",
      "API Development",
      "Flask",
      "Python (Programming Language)",
      "Full-Stack Development",
      "React.js",
      "Bootstrap (Framework)",
      "Web Development",
      "MySQL",
      "Database Management System (DBMS)",
    ],
    imageRefs: [],
    description:
      "A web application system integrating Flask, React.js, MySQL, and AdminLTE to help users efficiently manage day-to-day transactions, accounts, and expenditures. Built on a normalized SQL database with multiple constrained tables for secure, well-structured storage of transactions, account balances, and profile details. The React.js frontend features a dark-and-yellow color palette via AdminLTE and custom CSS, offering a seamless and highly interactive interface. Development paused in March 2025 to prioritize a more urgent academic project; also served to help the developer sharpen integration skills.",
    note: "",
    associatedWith: ["Don Bosco Technical College, Mandaluyong"],
  },
  {
    projectName: "Bosledger: Accounting & Registrar System",
    startDate: "2025-09",
    endDate: "2025-10",
    currentlyWorking: false,
    skills: [
      "PostgreSQL",
      "Cloud Computing",
      "React.js",
      "Tailwind CSS",
      "User Interface Design",
      "Full-Stack Development",
    ],
    imageRefs: [],
    description:
      "A cloud-integrated accounting and registrar system with role-based access control. Centralizes student records, enrollment status, and payment histories so students, registrars, and accounting staff can view balances, manage enrollments, and complete tasks from a single dashboard. Built-in reports and quick-action cards help resolve issues and process approvals faster, with a mobile-friendly, role-aware interface that surfaces relevant tools per user. Uses a TypeScript React frontend with a shared Supabase client for auth and data, React Query for caching, and Tailwind-based UI primitives. Architected for reuse and observability, with pages organized for easy extension.",
    note: "",
    associatedWith: [],
  },
  {
    projectName: "Apollo: Cross-Platform Fire Emergency Response System",
    startDate: "2025-01",
    endDate: "2025-11",
    currentlyWorking: false,
    skills: [
      "React.js",
      "React Native",
      "Flask",
      "Bootstrap (Framework)",
      "MySQL",
      "GitHub",
      "TensorFlow",
      "Machine Learning",
      "Amazon Web Services (AWS)",
    ],
    imageRefs: [],
    description:
      "A real-time fire monitoring mobile application developed for Capstone Project 1 & 2, in collaboration with the Daang Bakal Fire Station at Barangay Daang Bakal. Streamlines and speeds up the fire report submission process using mobile apps, geographic information systems (GIS), machine learning models, and REST APIs powered by Flask. Aims to improve communication between civilians and responders to save time, extinguish fires earlier, and protect more people and property.",
    note: "",
    associatedWith: ["Don Bosco Technical College, Mandaluyong"],
  },
  {
    projectName: "Estarossa",
    startDate: "2025-11",
    endDate: "2026-01",
    currentlyWorking: false,
    skills: [
      "Next.js",
      "Tailwind CSS",
      "API Development",
      "Full-Stack Development",
      "TypeScript",
      "Web Development",
      "Web Design",
      "Flask",
      "Web Applications",
    ],
    imageRefs: [],
    description:
      "A casual personal project modeled after current clinic web systems, using mostly mock data. Includes JWT authorization via cookies with flask-jwt-token and role-based access control. Tailwind CSS was used to build a proper landing page and dashboard layout, alongside developing Next.js proficiency with client-side rendering for pages and server-side rendering for requests to the Flask API. Involved building a custom Flask server architecture using blueprints, monkeypatch-based automated testing, auth middleware, data encryption/decryption, and a controller object inspired by Laravel 17. The database schema experimented with separating user authentication from user details and integrating audit logs within server operations, inspired by Supabase. Discontinued due to burnout, academic/career changes, and a desire to build beyond CRUD web applications.",
    note: "",
    associatedWith: [],
  },
  {
    projectName: "Qualisync",
    startDate: "2026-01",
    endDate: "2026-03",
    currentlyWorking: false,
    skills: [
      "GitHub",
      "Flask",
      "REST APIs",
      "MySQL",
      "Next.js",
      "Configuration Management",
      "Docker",
      "Container Orchestration",
      "pytest",
      "vitest",
      "JSON Web Token (JWT)",
      "Virtualization",
    ],
    imageRefs: [],
    description:
      "A full-stack DevOps and QA automation platform built to explore manual and automated QA, version control practices, development standards, virtualization, orchestration, cloud, and configuration management. Centered on Fuchsia ATMS, a fictional apartment-tenant management application with a Next.js frontend, Flask API backend, JWT authentication, and a normalized MySQL database. Used script-based linting and formatting (Black, Flake8, ESLint, Prettier) via pyproject.toml and package.json, with Pytest and Flask Test Client for API testing and Vitest for UI component/integration testing. Integrated Taskfile.yml to batch shell commands across root and service levels, and orchestrated custom Docker images per service via docker-compose.yml, including a dedicated MySQL image. Incorporated AI agent-based development using AGENTS.md and structured prompts in VS Code Copilot. Version-controlled with GitHub, including branching and workflows.",
    note: "",
    associatedWith: [],
  },
  {
    projectName: "Deter",
    startDate: "2026-03",
    endDate: "2026-04",
    currentlyWorking: false,
    skills: [
      "GitHub",
      "Docker",
      "TypeScript",
      "MySQL",
      "Cloud Computing",
      "Virtualization",
      "Full-Stack Development",
      "Git",
      "Linux",
      "Microsoft Azure",
      "Azure DevOps Services",
      "Laravel",
      "PHP",
      "DevOps",
      "Continuous Integration and Continuous Delivery (CI/CD)",
      "Nginx",
      "Redis",
      "Containerization",
      "Networking",
      "GitHub Copilot",
    ],
    imageRefs: [],
    description:
      "A cloud-native Laravel analytics application and CI/CD deployment pipeline built for data automation and analytics, using a monolithic Laravel backend with a React/Inertia frontend, spanning PHP, TypeScript/React, Vite, Tailwind CSS, and Bicep Infrastructure as Code. Features a containerized architecture with multi-stage Docker builds, Docker Compose orchestration, Nginx reverse proxying, PHP-FPM, and Supervisor process management. Built an automated GitHub Actions CI/CD pipeline for Docker image builds, Azure Container Registry pushes, and continuous deployment to Azure App Service. Provisioned enterprise-grade Azure infrastructure via Bicep IaC, including App Service, Container Registry, MySQL Flexible Server, Redis Cache, Virtual Networks, and private DNS, following GitOps practices. Includes a mock analytics dashboard with statistics, paginated/filterable user tables, data cleaning utilities (department normalization, duplicate detection), and license management with upgrade recommendations. Used Composer for PHP dependencies and pnpm with workspace configuration for a monorepo frontend, plus environment-based config management, GitHub Secrets for secret injection, and container-startup database migrations.",
    note: "",
    associatedWith: [],
  },
  {
    projectName: "Meridian Nexus",
    startDate: "2026-04",
    endDate: "2026-05",
    currentlyWorking: false,
    skills: [
      "React.js",
      "TypeScript",
      "GitHub",
      "Tailwind CSS",
      "PostgreSQL",
      "Next.js",
      "Continuous Integration and Continuous Delivery (CI/CD)",
      "YAML",
    ],
    imageRefs: [],
    description:
      "A simulated case-study ERP system built around a mock talent agency, Meridian Nexus Group Ltd, with business requirements based on real-life data and research, solved by a fictional ERP solution called Polaris Engine. Built as a full-stack web engine on Next.js App Router with React 19, combining server-rendered routes, client UI, and API handlers in one codebase. Used Supabase (PostgreSQL, Auth, Storage) with server-side SSR clients for secure session handling. Designed a role-aware security model using PostgreSQL RLS policies across guest, talent, client, ops, finance, admin, and superadmin roles for least-privilege data access. Modeled a domain-first relational schema (profiles, talents, clients, contracts, vaults, vault files, feedback) with enums, constraints, and timestamps for data integrity, and automated lifecycle workflows via database triggers such as auto-creating contract vaults on finalization. Centralized auth flow through Next.js API routes and middleware-based route protection, with a CI/CD-ready stack via GitHub workflows and Vercel deployment hooks. Development became increasingly difficult as a solo developer working with PostgreSQL and Next.js's App Router structure, compounded by repeated Supabase rate limiting that blocked access to the app even in development, and growing friction switching between development and deployment environments.",
    note: "",
    associatedWith: [],
  },
  {
    projectName: "Leuchtturm",
    startDate: "2026-05",
    endDate: "2026-06",
    currentlyWorking: false,
    skills: [
      "React.js",
      "Python (Programming Language)",
      "PHP",
      "Laravel",
      "TypeScript",
      "Next.js",
      "Google Gemini",
      "Retrieval-Augmented Generation (RAG)",
      "FastAPI",
      "Inertia.js",
      "Vector Databases",
      "LangChain",
      "Ollama",
    ],
    imageRefs: [],
    description:
      "A RAG-based chatbot system centered on a codebase-aware AI chatbot for discourse and interaction. Includes Yellowpad, a simple customizable notepad storage app where users create notepads and add rows like checkboxes, list items, or flagged variants. Also includes Leuchtturm UI, a minimalist chat-based web application for creating conversations with the AI and sending messages or queries about Yellowpad. Designed Sumerian, a full RAG-centric pipeline covering codebase scanning, vector embedding, and text response generation, connected via a centralized FastAPI server that links the chat service to the RAG pipeline and codebase.",
    note: "",
    associatedWith: [],
  },
  {
    projectName: "Snapshot",
    startDate: "2026-06",
    endDate: "",
    currentlyWorking: true,
    skills: ["Next.js", "TypeScript", "Tailwind CSS", "React.js"],
    imageRefs: [],
    description:
      "The official web portfolio of Miguel Justin Bunda, showcasing his work, experience, education, and personal reflections on the tech industry — clean and minimal by design, but built with intention. Built with TypeScript, Next.js, Tailwind CSS, and Lucide Icons, hosted on Vercel at migueljustin.vercel.app. Features a scrollable landing page with rich visuals and interactive components, with select sections expanding into dedicated subpages, each with its own distinct design. Fully responsive across web, tablet, and mobile, with light and dark mode that automatically adapts to device settings. Includes direct links to GitHub, LinkedIn, and other contact channels.",
    note: "",
    associatedWith: [],
  },
];
