import { Server, Network, FileCode2, Braces, Binary, Code2, Database, Table2, Triangle, Smartphone, Layers, FlaskConical, Rocket, BrainCircuit, Wind, Zap, Box, Container, GitBranch, GitCommit, Workflow, ScrollText, Terminal, Cloud, CloudCog, HardDrive, BookOpen, Briefcase, GraduationCap, LucideIcon } from "lucide-react";
import { SkillCategory, Skill, SkillSource } from "../types/skills";

export const sourceMeta: Record<SkillSource, { label: string; icon: LucideIcon }> = {
    school: { label: "School", icon: GraduationCap },
    "self-study": { label: "Self-Study", icon: BookOpen },
    internship: { label: "Internship", icon: Briefcase },
};

export const skillData: Record<SkillCategory, Skill[]> = {
    languages: [
        {
            name: "TypeScript",
            icon: FileCode2,
            timeSpent: "2 yrs",
            preferred: true,
            description: "Used across full-stack projects for type-safe frontend and backend development.",
            sources: ["school", "self-study", "internship"],
        },
        {
            name: "JavaScript",
            icon: Braces,
            timeSpent: "1 yrs",
            description: "Brief usage before jumping ship to TypeScript, though have proficiency due to having similar syntax to TS.",
            sources: ["school", "self-study", "internship"],
        },
        {
            name: "Python",
            icon: Binary,
            timeSpent: "4 yrs",
            description: "Applied in backend services, automation scripts, and ML-driven projects.",
            sources: ["school", "self-study"],
        },
        {
            name: "PHP",
            icon: Code2,
            timeSpent: "1 yr",
            description: "Used with Laravel for backend prototyping, coursework, and rapid development of projects.",
            sources: ["school"],
        },
        {
            name: "MariaDB",
            icon: Database,
            timeSpent: "3 yrs",
            description: "First database query language where I learned joins, query building, and optimization.",
            sources: ["school", "self-study"],
        },
        {
            name: "PostgreSQL",
            icon: Table2,
            timeSpent: "1 yr",
            description: "Primary relational database for Supabase-backed projects like Bosledger and Meridian Nexus.",
            sources: ["self-study"],
        },
    ],
    frameworks: [
        {
            name: "Next.js",
            icon: Triangle,
            timeSpent: "1 yr",
            preferred: true,
            description: "Primary framework for building this portfolio and other full-stack apps.",
            sources: ["self-study", "internship"],
        },
        {
            name: "React Native (Expo)",
            icon: Smartphone,
            timeSpent: "9 mos",
            description: "Built the camera-first mobile reporting app for the Apollo fire response platform.",
            sources: ["self-study"],
        },
        {
            name: "Node.js (Express)",
            icon: Server,
            timeSpent: "1 yr",
            description: "Used Node as runtime environment while self-studied Express.js pre-Python dev.",
            sources: ["self-study"],
        },
        {
            name: "Laravel",
            icon: Layers,
            timeSpent: "6 mos",
            description: "Explored PHP-based backend development in coursework and in internship.",
            sources: ["school", "internship"],
        },
        {
            name: "Flask",
            icon: FlaskConical,
            timeSpent: "3 yr",
            preferred: true,
            description: "Go-to Python backend framework across Estarossa, Midas, Cerebral, and many more.",
            sources: ["school", "self-study"],
        },
        {
            name: "FastAPI",
            icon: Rocket,
            timeSpent: "3 mos",
            description: "Experimented with async-first API development as an alternative to Flask.",
            sources: ["self-study"],
        },
        {
            name: "TensorFlow",
            icon: BrainCircuit,
            timeSpent: "6 mos",
            description: "Trained and integrated ML models for the Apollo fire classification pipeline.",
            sources: ["school", "self-study"],
        },
        {
            name: "Tailwind CSS",
            icon: Wind,
            timeSpent: "1 yr",
            preferred: true,
            description: "Primary styling approach across all recent full-stack projects.",
            sources: ["school", "self-study", "internship"],
        },
        {
            name: "Vite",
            icon: Zap,
            timeSpent: "1 yr",
            description: "Preferred build tool for lighter-weight React projects and prototypes.",
            sources: ["self-study"],
        },
        {
            name: "Supabase",
            icon: Box,
            timeSpent: "8 mos",
            description: "Backend-as-a-Service powering auth, database, and storage for Bosledger and Meridian Nexus.",
            sources: ["school", "self-study"],
        },
    ],
    tools: [
        {
            name: "Docker",
            icon: Container,
            timeSpent: "2 yr",
            description: "Used to containerize testing environments and deployment pipelines.",
            sources: ["school", "internship", "self-study"],
        },
        {
            name: "Git",
            icon: GitBranch,
            timeSpent: "3 yrs",
            description: "Version control across all school, personal, and internship projects.",
            sources: ["school", "self-study", "internship"],
        },
        {
            name: "GitHub",
            icon: GitCommit,
            timeSpent: "3 yrs",
            description: "Managed repos, reviews, and CI/CD workflows for personal and internship projects.",
            sources: ["school", "self-study", "internship"],
        },
        {
            name: "GitHub Actions",
            icon: Workflow,
            timeSpent: "1 yr",
            description: "Built automated pipelines for testing and deployment.",
            sources: ["self-study", "internship"],
        },
        {
            name: "Azure Bicep",
            icon: ScrollText,
            timeSpent: "6 mos",
            description: "Provisioned Azure infrastructure as code during internship deployment work.",
            sources: ["internship"],
        },
        {
            name: "Terraform",
            icon: Network,
            timeSpent: "1 mo",
            description: "Briefly explored as an alternative IaC tool for multi-cloud provisioning.",
            sources: ["self-study"],
        },
        {
            name: "Bash",
            icon: Terminal,
            timeSpent: "2 yrs",
            description: "Used for scripting automation tasks and managing Linux environments.",
            sources: ["self-study", "internship"],
        },
    ],
    platforms: [
        {
            name: "Microsoft Azure",
            icon: Cloud,
            timeSpent: "8 mos",
            description: "Deployed CRM infrastructure and CI/CD pipelines during various projects.",
            sources: ["self-study", "internship"],
        },
        {
            name: "Amazon Web Services",
            icon: CloudCog,
            timeSpent: "6 mos",
            description: "Hosted the Apollo platform's ML inference backend on EC2 Instances.",
            sources: ["school", "self-study"],
        },
        {
            name: "Linux (Ubuntu)",
            icon: HardDrive,
            timeSpent: "2 yrs",
            description: "Daily driver for development and server administration.",
            sources: ["self-study", "school"],
        },
    ],
};